### ISSUE TITLE
When Kafka is enabled, the FastAPI/HTTP endpoint doesn't work

### ISSUE THREAD

**Issue by chgl** [miracum/ahd2fhir#21]
This is probably some issue with asyncio, since both AIOKafka and FastAPI are using a/the same event loop. This might have been introduced by https://github.com/miracum/ahd2fhir/commit/8bb6918f4e3eb303abe4e54fb85e196cea0a1413

**Comment by uklft** [comment]
Problem seems to be solved by #22.
