### ISSUE TITLE
Update ahd2fhir to be compatible with AHDv6

### ISSUE THREAD

**Issue by makampf** [miracum/ahd2fhir#67]
- https://help.averbis.com/display/AKB/Health+Discovery+Version+6.0-RC
- https://help.averbis.com/pages/viewpage.action?pageId=40799961

**Comment by chgl** [comment]
See also https://github.com/miracum/ahd2fhir/issues/19 particularly https://github.com/miracum/ahd2fhir/issues/19#issuecomment-1103203825
